name: Create Branch For Issue
on:
  issues:
    # 이슈 담당자존재할때, 오픈, 재오픈 할때 이벤트 발생
    types: [assigned, opened, reopened]
  issue_comment:
    # 이슈 코멘트가 생성될때
    types: [created]
  pull_request:
    # PR이 opend, closed 이벤트 발생시
    types: [opened, closed]
    branches:
      - develop
      - 'trazzle/ios-**'

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 생성
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.POTENTIAL_GH_TOKEN }}
